
# cargo-vet config file

[cargo-vet]
version = "0.9"

[[exemptions.byteorder]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.11.0"
criteria = "safe-to-deploy"

[[exemptions.hash32]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.heapless]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.81"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.36"
criteria = "safe-to-deploy"

[[exemptions.stable_deref_trait]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.60"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "1.0.59"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.59"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.12"
criteria = "safe-to-deploy"
